version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    environment:
      DB_HOST: db
    ports:
      - '8000:80'
    links:
      - db:db
  db:
    image: mysql:5.6
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secaimarche
      MYSQL_DATABASE: secaimarche
      MYSQL_USER: secaimarche
      MYSQL_PASSWORD: secaimarche
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  data:
    driver: local